# **Data Pre-Processing**

## 1. Introduction

## 2. Combining Dataset of All Jabodetabek

In [20]:
import pandas as pd
import numpy as np
from numpy import vectorize
import ast

In [21]:
file_names = [
    'Scraped_Data/raw/Bekasi_2022-10-09_16-57_page_1_to_50.csv',
    'Scraped_Data/raw/Bogor_2022-10-08_17-49_page_1_to_20.csv',
    'Scraped_Data/raw/Bogor_2022-10-08_18-19_page_21_to_30.csv',
    'Scraped_Data/raw/Bogor_2022-10-09_18-20_page_31_to_50.csv',
    'Scraped_Data/raw/Depok_2022-10-09_17-17_page_1_to_21.csv',
    'Scraped_Data/raw/Depok_2022-10-09_14-23_page_22_to_50.csv',
    'Scraped_Data/raw/Jakarta_2022-10-07_08-14_page_1_to_10.csv',
    'Scraped_Data/raw/Jakarta_2022-10-08_13-34_page_11_to_20.csv',
    'Scraped_Data/raw/Jakarta_2022-10-09_17-20_page_21_to_37.csv',
    'Scraped_Data/raw/Jakarta_2022-10-08_15-00_page_38_to_40.csv',
    'Scraped_Data/raw/Jakarta_2022-10-08_15-41_page_41_to_50.csv',
    'Scraped_Data/raw/Tangerang_2022-10-08_21-10_page_1_to_50.csv'
]

df = pd.concat(
    map(pd.read_csv, file_names), ignore_index=True
)

df.sample(2).T

,2888,2803
url,https://www.rumah123.com/properti/tangerang/ho...,https://www.rumah123.com/properti/tangerang/ho...
currency,Rp,Rp
price,"10,1","4,44"
price_unit_scale,Miliar,Miliar
title,Rumah Mewah 3 Lantai Di Kawasan Zora Bsd City,RUMAH VIEW DANAU FULL MARMER! SUTERA WINONA AL...
address,"BSD City, Tangerang","Alam Sutera, Tangerang"
facilities,"Keamanan 24 jam, AC, Kolam Renang, Taman, On...","Jogging Track, Taman, Kolam Renang, CCTV, Ja..."
k. tidur,4.00,5.00
k. mandi,4.00,6.00
l. tanah,200 m²,108 m²
l. bangunan,358 m²,195 m²
tipe properti,rumah,rumah
sertifikat,NaN,shm - sertifikat hak milik
daya listrik,7700 mah,3500 mah
km. pembantu,NaN,1.00
jumlah lantai,NaN,3.00
tahun dibangun,NaN,"2,020.00"
kondisi properti,NaN,bagus sekali
kondisi perabotan,NaN,semi furnished
id iklan,NaN,hos7103414
carport,2.00,2.00
hadap,NaN,selatan
garasi,NaN,2.00
kt. pembantu,NaN,1.00
bedrooms,NaN,NaN
bathrooms,NaN,NaN
land size,NaN,NaN
building size,NaN,NaN
carports,NaN,NaN
certificate,NaN,NaN
electricity,NaN,NaN
maid bedrooms,NaN,NaN
maid bathrooms,NaN,NaN
floors,NaN,NaN
building age,NaN,NaN
property condition,NaN,NaN
building orientation,NaN,NaN
garages,NaN,NaN
furnishing,NaN,NaN

## 3. Column Field Correction

As we can see, there are inconsistence column labels due to different language format. Let's compare both condition:

In [22]:
list((df[~(df['k. tidur'].isna())].sample(1).index.values,
        df[~(df['bedrooms'].isna())].sample(1).index.values)
)

[array([3023], dtype=int64), array([2894], dtype=int64)]

In [23]:
sample = pd.concat([
        df[(df['k. tidur'].notnull())].sample(1),
        df[(df['bedrooms'].notnull())].sample(1)
])

sample.T

,68,830
url,https://www.rumah123.com/properti/bekasi/hos11...,https://www.rumah123.com/properti/bogor/hos108...
currency,Rp,Rp
price,300,260
price_unit_scale,Juta,Juta
title,Rumah murah di bekasi kebalen vgh babelan!!,Jual rumah murah siap huni ..
address,"Kebalen, Bekasi","Dramaga, Bogor"
facilities,"Jogging Track, Track Lari, Masjid, Keamanan 2...","Taman, Masjid, Keamanan"
k. tidur,2.00,NaN
k. mandi,1.00,NaN
l. tanah,60 m²,NaN
l. bangunan,36 m²,NaN
tipe properti,rumah,rumah
sertifikat,shm - sertifikat hak milik,NaN
daya listrik,1300 mah,NaN
km. pembantu,NaN,NaN
jumlah lantai,1.00,NaN
tahun dibangun,"2,022.00",NaN
kondisi properti,baru,NaN
kondisi perabotan,unfurnished,NaN
id iklan,hos11208968,hos10849438
carport,1.00,NaN
hadap,timur,NaN
garasi,NaN,NaN
kt. pembantu,NaN,NaN
bedrooms,NaN,4.00
bathrooms,NaN,2.00
land size,NaN,100 m²
building size,NaN,70 m²
carports,NaN,NaN
certificate,NaN,"lainnya (ppjb,girik,adat,dll)"
electricity,NaN,1300 mah
maid bedrooms,NaN,NaN
maid bathrooms,NaN,NaN
floors,NaN,1.00
building age,NaN,"2,019.00"
property condition,NaN,baru
building orientation,NaN,barat
garages,NaN,NaN
furnishing,NaN,NaN

In [24]:
row_count = pd.DataFrame({
    'row_count' : [
        df[df['k. tidur'].notnull()].shape[0],
        df[df['bedrooms'].notnull()].shape[0]
        ]
    })
row_count.index=['ind_labeled', 'eng_labeled']
row_count

             row_count
ind_labeled       3409
eng_labeled        110

As we can see, where `Indonesian labeled column` is recorded, the `English labeled column` is empty, and vice versa. I decide to keep the English label using codes below:

In [25]:
label_pair = [
    ('k. tidur', 'bedrooms'),
    ('k. mandi', 'bathrooms'),
    ('l. tanah', 'land size'),
    ('l. bangunan', 'building size'),
    ('sertifikat', 'certificate'),
    ('daya listrik', 'electricity'),
    ('km. pembantu', 'maid bathrooms'),
    ('jumlah lantai', 'floors'),
    ('tahun dibangun', 'building age'),
    ('kondisi properti', 'property condition'),
    ('kondisi perabotan', 'furnishing'),
    ('carport', 'carports'),
    ('hadap', 'building orientation'),
    ('garasi', 'garages'),
    ('kt. pembantu', 'maid bedrooms')
]

We will use `DataFrame.fillna()` (column-wise) to fill missing records of `English labeled columns` using `Indonesian labeled columns` value as below:

In [26]:
for ind, eng in label_pair:
    df[eng].fillna(value=df[ind], inplace=True)
df.sample(2).T

,3147,1647
url,https://www.rumah123.com/properti/tangerang/ho...,https://www.rumah123.com/properti/depok/hos109...
currency,Rp,Rp
price,650,750
price_unit_scale,Juta,Juta
title,Termurah Rumah 2 Lantai Siap Huni di Karawaci ...,Rumah Minimalis di Palm Residence Dekat Park S...
address,"Karawaci, Tangerang","Sawangan, Depok"
facilities,"Masjid, Keamanan 24 jam, Tempat Jemuran","Keamanan, Taman"
k. tidur,3.00,1.00
k. mandi,2.00,1.00
l. tanah,72 m²,72 mÂ²
l. bangunan,96 m²,43 mÂ²
tipe properti,rumah,rumah
sertifikat,shm - sertifikat hak milik,shm - sertifikat hak milik
daya listrik,1300 mah,1300 mah
km. pembantu,NaN,NaN
jumlah lantai,2.00,1.00
tahun dibangun,NaN,NaN
kondisi properti,bagus,bagus
kondisi perabotan,unfurnished,unfurnished
id iklan,hos11251201,hos10916403
carport,1.00,1.00
hadap,NaN,timur laut
garasi,1.00,NaN
kt. pembantu,NaN,1.00
bedrooms,3.00,1.00
bathrooms,2.00,1.00
land size,72 m²,72 mÂ²
building size,96 m²,43 mÂ²
carports,1.00,1.00
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,1300 mah,1300 mah
maid bedrooms,NaN,1.00
maid bathrooms,NaN,NaN
floors,2.00,1.00
building age,NaN,NaN
property condition,bagus,bagus
building orientation,NaN,timur laut
garages,1.00,NaN
furnishing,unfurnished,unfurnished

Looks like it turns out as we expected. Now we just drop the `Indonesian labeled columns` using below codes. We also rename the columns that still in Indonesian label and using `snake_case` format:

In [27]:
for column in label_pair:
    df.drop(labels=column[0], axis=1, inplace=True)

df.rename(
    columns={
        'tipe properti': 'property_type',
        'id iklan': 'ads_id'
        }, 
    inplace=True
)

df.rename(
    columns={
        column: column.replace(' ', '_') for column in df.columns
    },
    inplace=True
)

df.sample(2).T

,2759,3249
url,https://www.rumah123.com/properti/tangerang/ho...,https://www.rumah123.com/properti/tangerang/ho...
currency,Rp,Rp
price,500,"7,2"
price_unit_scale,Juta,Miliar
title,Rumah Bebas Banjir Di Perumahan Citra Raya Har...,"Rumah Mewah Dijual di Bsd City, Tangerang, Banten"
address,"Panongan, Tangerang","BSD The Icon, Tangerang"
facilities,"Keamanan, Taman",CCTV
property_type,rumah,rumah
ads_id,hos10597643,hos10773553
bedrooms,2.00,4.00
bathrooms,1.00,4.00
land_size,72 m²,224 m²
building_size,50 m²,350 m²
carports,1.00,2.00
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,1300 mah,3500 mah
maid_bedrooms,NaN,1.00
maid_bathrooms,NaN,1.00
floors,1.00,3.00
building_age,NaN,"2,022.00"
property_condition,bagus,baru
building_orientation,NaN,selatan
garages,1.00,NaN
furnishing,unfurnished,NaN

## 4. Transforming Price and Address Records

#### **Price Records**

We are going to check unique values of `currency` and `price_unit_scale`:

In [28]:
print(df.currency.unique())
print(df.price_unit_scale.unique())

['Rp']
['Miliar' 'Juta' 'Triliun']

We should check the house price in `Triliun`, since the value is rather ambiguous for a house price to be this high.

In [29]:
df[df.price_unit_scale=='Triliun']

,url,currency,price,price_unit_scale,title,address,facilities,property_type,ads_id,bedrooms,...,certificate,electricity,maid_bedrooms,maid_bathrooms,floors,building_age,property_condition,building_orientation,garages,furnishing
934,https://www.rumah123.com/properti/bogor/hos113...,Rp,"5,4",Triliun,"Rumah di Baranang Siang Indah, Dekat Tol, Mal,...","Baranangsiang, Bogor","Taman, Keamanan 24 jam, Taman, CCTV, Masjid,...",rumah,hos11359992,3.00,...,shm - sertifikat hak milik,5500 mah,1.00,1.00,2.00,NaN,bagus,timur,1.00,unfurnished

After checking the URL, seems that price is in Rp. 5,4 Miliar (listing may be revised by owner) so we shall revise the price scale for this record.

In [30]:
df.loc[df.price_unit_scale=='Triliun', 'price_unit_scale'] = 'Miliar'
print(df.price_unit_scale.unique())

['Miliar' 'Juta']

The price is still in `string` format, so we will transform the value by its `price_unit_scale`.

Pandas need `vectorized function` to execute `vectorized operations`. We can create `vectorized function` by creating a standard function first then we convert it into vectorized function using `np.vectorize`. Note that `np.vectorize` returns a `callable` as its output, which we will use to our Pandas operations.

In [31]:
def convert_price(price: str, unit_scale: str):
    price_numeric = float(price.replace(',', '.'))
    if unit_scale == 'Juta':
        converted_price = price_numeric * 1000000
    else:
        converted_price = price_numeric * 1000000000
    return converted_price

convert_price_vectd = vectorize(convert_price)

Let's try our `vectorized function` to our dataframe. It is convenient to change panda's setting of number display format so that we can clearly distinguish the millions and billions scale.

In [32]:
pd.set_option('display.float_format', '{:,.2f}'.format)

df.assign(
    price_converted=convert_price_vectd(df.price, df.price_unit_scale)
).loc[:, ['currency', 'price', 'price_unit_scale', 'price_converted']].sample(3, random_state=4).T

                             1893           1739             3275
currency                       Rp             Rp               Rp
price                        1,67            800              2,4
price_unit_scale           Miliar           Juta           Miliar
price_converted  1,670,000,000.00 800,000,000.00 2,400,000,000.00

As expected, `Pandas` performing vectorized function, resulting in an index-wise operation to convert the price. The scale of `Miliar` and `Juta` is also correct as expected.

We won't need the `price_unit_scale` anymore, and we will define a new column `price_in_rp` to inform that the currency is in `Rupiahs`.

In [33]:
df = df.assign(
    price = convert_price_vectd(df.price, df.price_unit_scale)
    ).rename(
        columns={'price': 'price_in_rp'}
    ).drop(
        ['currency', 'price_unit_scale'], axis=1
    )

df.sample(2).T

,1794,2751
url,https://www.rumah123.com/properti/depok/hos111...,https://www.rumah123.com/properti/tangerang/ho...
price_in_rp,"800,000,000.00","1,860,000,000.00"
title,Rumah 2 Lantai SHM Semi Furnished di Rangkapan...,Rumah Strategis Bebas Banjir di Perumahan Banj...
address,"Pancoran Mas, Depok","Pinang, Tangerang"
facilities,"Jalur Telepon, Ac, AC, Track Lari, Taman, ...","Keamanan, Taman"
property_type,rumah,rumah
ads_id,hos11130573,hos10612663
bedrooms,3.00,3.00
bathrooms,2.00,3.00
land_size,70 mÂ²,144 m²
building_size,72 mÂ²,100 m²
carports,2.00,NaN
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,2200 mah,2200 mah
maid_bedrooms,NaN,NaN
maid_bathrooms,NaN,NaN
floors,2.00,1.00
building_age,"2,022.00",NaN
property_condition,baru,NaN
building_orientation,timur,NaN
garages,2.00,1.00
furnishing,semi furnished,unfurnished

#### **Address**

Address records contains (`district`, `city`). Splitting into this may be useful when reporting insight, so I will also provide the separate value of this.

In [34]:
def get_district(address:str):
    return address.strip().split(sep=',')[0]

def get_city(address:str):
    return address.strip().split(sep=',')[1]

get_district_vectd = vectorize(get_district)
get_city_vectd = vectorize(get_city)

In [35]:
df.assign(
    district=get_district_vectd(df.address),
    city=get_city_vectd(df.address)
).loc[:, ['address', 'district', 'city']].sample(3).T

                           72               1896            438
address   Harapan Indah, Bekasi  Sawangan, Depok  Bekasi, Bekasi
district          Harapan Indah         Sawangan          Bekasi
city                     Bekasi            Depok          Bekasi

Results is as expected. We will apply this to our Dataframe, and positions the `district` and `city` next to the `address` for convenience.

In [36]:
columns_pair = [('city', get_city_vectd), ('district', get_district_vectd)]
for (col, func) in columns_pair:
    df.insert(4, col, func(df.address))

df.sample(2).T

,1840,2777
url,https://www.rumah123.com/properti/depok/hos113...,https://www.rumah123.com/properti/tangerang/ho...
price_in_rp,"484,000,000.00","3,830,000,000.00"
title,"Rumah di Jalan Raya Bojongsari, Sawangan Depok",Rumah Cluster Narada Nykka Tangerang
address,"Bojong Sari, Depok","Alam Sutera, Tangerang"
district,Bojong Sari,Alam Sutera
city,Depok,Tangerang
facilities,"AC, Masjid, CCTV, Kulkas, Wastafel, Pemanas...","Ac, Keamanan, Taman, CCTV, Jogging Track, J..."
property_type,rumah,rumah
ads_id,hos11323823,hos11132549
bedrooms,2.00,3.00
bathrooms,1.00,3.00
land_size,72 mÂ²,105 m²
building_size,45 mÂ²,134 m²
carports,1.00,1.00
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,1300 mah,3500 mah
maid_bedrooms,NaN,1.00
maid_bathrooms,NaN,1.00
floors,1.00,2.00
building_age,"2,022.00","2,022.00"
property_condition,baru,baru
building_orientation,utara,selatan
garages,NaN,NaN
furnishing,semi furnished,NaN

In notebook `1. Web Scraping`, we also scrap `estimated latitude and longitude` of each district, because the primary website doesn't provide any coordinate information.

We are going to join the `latitude and longitude` data using below codes. `Adress` column will be used as the `join key`.

In [37]:
lat_long_df = pd.read_csv('Scraped_Data/lat_long_complete.csv')
lat_long_df.head()

,address,lat_long,gmaps_tag
0,"Bekasi, Bekasi","(-6.2849775, 106.970127)","Kota Bks, Jawa Barat"
1,"Setu, Bekasi","(-6.358777, 107.0348331)","Kec. Setu, Kabupaten Bekasi, Jawa Barat"
2,"Harapan Indah, Bekasi","(-6.1817523, 106.9736839)","Harapan Indah, RT.005/RW.010, Medan Satria, Ke..."
3,"Bekasi Kota, Bekasi","(-6.2845395, 106.973377)","Bekasi, Kota Bks, Jawa Barat"
4,"Cibitung, Bekasi","(-6.243801, 107.1036725)","Kec. Cibitung, Kabupaten Bekasi, Jawa Barat"

In [38]:
def split_lat_long(value):
    lat_long = ast.literal_eval(value)
    return lat_long

split_lat_long_vectd = vectorize(split_lat_long)
lat_long_df = lat_long_df.assign(
    lat=split_lat_long_vectd(lat_long_df.lat_long)[0],
    long=split_lat_long_vectd(lat_long_df.lat_long)[1],
)
lat_long_df.head()

,address,lat_long,gmaps_tag,lat,long
0,"Bekasi, Bekasi","(-6.2849775, 106.970127)","Kota Bks, Jawa Barat",-6.28,106.97
1,"Setu, Bekasi","(-6.358777, 107.0348331)","Kec. Setu, Kabupaten Bekasi, Jawa Barat",-6.36,107.03
2,"Harapan Indah, Bekasi","(-6.1817523, 106.9736839)","Harapan Indah, RT.005/RW.010, Medan Satria, Ke...",-6.18,106.97
3,"Bekasi Kota, Bekasi","(-6.2845395, 106.973377)","Bekasi, Kota Bks, Jawa Barat",-6.28,106.97
4,"Cibitung, Bekasi","(-6.243801, 107.1036725)","Kec. Cibitung, Kabupaten Bekasi, Jawa Barat",-6.24,107.10

In [39]:
# merge dataframes
df = df.merge(
    right=lat_long_df.loc[:, ['address', 'lat', 'long']],
    on='address'
)
# re-arrange columns
cols = df.columns.to_list()
cols.insert(6, 'long')
cols.insert(6, 'lat')
cols_arranged = cols.copy()[:-2]
df = df[cols_arranged]

df.sample(2).T

,1639,2244
url,https://www.rumah123.com/properti/depok/hos676...,https://www.rumah123.com/properti/jakarta-bara...
price_in_rp,"630,000,000.00","2,400,000,000.00"
title,Prestige Bojongsari Sawangan Rumah Dp 0 Persen,Axel Termurah Terlangka Jarang Ada Glc West Eu...
address,"Bojong Sari, Depok","Green Lake City, Jakarta Barat"
district,Bojong Sari,Green Lake City
city,Depok,Jakarta Barat
lat,-6.40,-6.19
long,106.74,106.70
facilities,"Jalur Telepon, Jogging Track, Tempat Jemuran...","Keamanan 24 jam, Kolam Renang, Taman, Playgr..."
property_type,rumah,rumah
ads_id,hos6761852,hos11249282
bedrooms,3.00,3.00
bathrooms,1.00,3.00
land_size,72 mÂ²,90 m²
building_size,52 mÂ²,120 m²
carports,1.00,2.00
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,2200 mah,4400 mah
maid_bedrooms,1.00,1.00
maid_bathrooms,NaN,1.00
floors,2.00,2.00
building_age,"2,022.00",NaN
property_condition,baru,bagus
building_orientation,utara,NaN
garages,1.00,NaN
furnishing,unfurnished,semi furnished

#### **Land Size, Building Size, Electricity**

Records of these columns is still in `string` format as (`value`, `unit`). We will extract only the number and rename the columns to inform the unit.

In [40]:
def get_value(value:str):
    if (type(value) == str):
        return float(value.strip().split(sep=' ')[0])
    else:
        return float(value)
    
get_value_vectd = vectorize(get_value)

In [41]:
df = df.assign(
    land_size=get_value_vectd(df.land_size),
    building_size=get_value_vectd(df.building_size),
    ).rename(
        columns={
            'land_size': 'land_size_m2',
            'building_size': 'building_size_m2'
        }
    )

df.sample(2).T

,3379,3505
url,https://www.rumah123.com/properti/tangerang/ho...,https://www.rumah123.com/properti/tangerang/ho...
price_in_rp,"4,890,000,000.00","3,750,000,000.00"
title,Rumah Luas 2 Lantai Lokasi Premium di Gading S...,*DIJUAL*\n\nRumah di Puspitaloka\nKantong semar
address,"Gading Serpong IL Lago, Tangerang","BSD Puspita Loka, Tangerang"
district,Gading Serpong IL Lago,BSD Puspita Loka
city,Tangerang,Tangerang
lat,-6.26,-6.29
long,106.56,106.67
facilities,"Keamanan, CCTV, Taman, Ac, Kolam Renang, J...","Taman, Jogging Track, Lapangan Basket, Keaman..."
property_type,rumah,rumah
ads_id,hos10790528,hos11360008
bedrooms,3.00,4.00
bathrooms,3.00,2.00
land_size_m2,180.00,299.00
building_size_m2,217.00,300.00
carports,2.00,1.00
certificate,NaN,shm - sertifikat hak milik
electricity,4400 mah,2200 mah
maid_bedrooms,1.00,2.00
maid_bathrooms,1.00,1.00
floors,2.00,2.00
building_age,NaN,"2,010.00"
property_condition,baru,sudah renovasi
building_orientation,timur laut,barat daya
garages,NaN,NaN
furnishing,unfurnished,unfurnished

Let's inspect the `electricity`. The category of electricity power for residential in Indonesia should not varied vastly.

In [42]:
df.electricity.unique()

array(['4400 mah', '2200 mah', '3500 mah', '1300 mah', nan, '5500 mah',
       '6600 mah', '7700 mah', '3300 mah', '7600 mah', 'lainnya mah',
       '10600 mah', '900 mah', '47500 mah', '11000 mah', '8000 mah',
       '450 mah', '10000 mah', '53000 mah', '16500 mah', '13200 mah',
       '13900 mah', '17600 mah', '23000 mah', '41500 mah', '12700 mah',
       '13300 mah', '33000 mah', '24000 mah', '22000 mah', '9500 mah'],
      dtype=object)

Later we can replace the missing `nan` value with `lainnya mah`. And also, the electricity is naturally has an `ordinal` order, which must be considered in later analysis.

#### **Building Age**

Let's inspect the `Building Age` columns:

In [43]:
df.building_age.unique()

array([ 2017.,    nan,  2016.,  2013.,  2014.,  2015.,  2022.,  2020.,
        2010.,  2018.,  2011.,  2021.,  2006.,  2000.,  2023.,  2019.,
        2007.,  2009.,  2012.,  2004.,  1985.,  2008.,  2001.,  2005.,
        1994.,  2003.,  2052.,  2002.,  2024.,  1995.,  1870.,  1970.,
        2025.,  1986.,  1980.,  1996.,  1993., 20010.,  1990.,  1999.,
       20012.,  1988.,  1982.,  1998.,  1976.,  1977.,  1973.,  1901.,
        1992.])

Some concerns:

1. Based on its values, it is best to be explained as `year_built`. We will rename the columns.
2. Unfortunately we don't find the `date listed` information in the listing info since it is best to explain *what owner think their house priced in the year that the house is listed and also considering house age since first it been built*. But it is okay to assumme that at the time the listing is still advertised in the website then owner *did* consider the value adhere to current year valuation. So we can extract `building_age = year_built - 2022`.  
3. There are some values that ambiguous: `2052, 20010, 20012, 2025`. For values `2025`, it may be because house is available after future housing project will be completed at `2025` (but this justification is still not make sense for `2052`)

In [44]:
df.rename(
    columns={'building_age': 'year_built'},
    inplace=True
)

In [45]:
years = [2052, 20010, 20012, 2025]
df[df.year_built.isin(years)].T

,761,1571,2119,2287
url,https://www.rumah123.com/properti/bogor/hos111...,https://www.rumah123.com/properti/depok/hos113...,https://www.rumah123.com/properti/jakarta-utar...,https://www.rumah123.com/properti/jakarta-sela...
price_in_rp,"570,000,000.00","370,000,000.00","7,700,000,000.00","106,000,000,000.00"
title,rumah 1 Lanta murah angsuran 2jutaan,RUMAH MEWAH DENGAN DESAIN EROPA MURAH DI CITAYAM,"Rumah Bukit Golf Mediterania, 2.5 Lantai, Pant...",Rumah murah di jalan widya chandra senayan keb...
address,"Sentul City, Bogor","Citayam, Depok","Pantai Indah Kapuk, Jakarta Utara","Kebayoran Baru, Jakarta Selatan"
district,Sentul City,Citayam,Pantai Indah Kapuk,Kebayoran Baru
city,Bogor,Depok,Jakarta Utara,Jakarta Selatan
lat,-6.52,-6.44,-6.10,-6.24
long,106.85,106.74,106.74,106.80
facilities,"Jalur Telepon, Tempat Jemuran, One Gate Syst...","Tempat Jemuran, Akses Parkir, One Gate Syste...","Keamanan 24 jam, Akses Parkir, Jalur Telepon, ...","Kolam Renang, Taman, Jalur Telepon, CCTV, K..."
property_type,rumah,rumah,rumah,rumah
ads_id,hos11148142,hos11336748,hos11153674,hos11260904
bedrooms,2.00,NaN,4.00,4.00
bathrooms,1.00,1.00,3.00,5.00
land_size_m2,72.00,65.00,180.00,"1,479.00"
building_size_m2,45.00,36.00,250.00,"1,000.00"
carports,1.00,1.00,2.00,4.00
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,1300 mah,1300 mah,NaN,11000 mah
maid_bedrooms,NaN,NaN,1.00,2.00
maid_bathrooms,NaN,NaN,1.00,2.00
floors,1.00,1.00,3.00,1.00
year_built,"2,052.00","2,025.00","20,010.00","20,012.00"
property_condition,baru,baru,butuh renovasi,bagus
building_orientation,timur,selatan,utara,selatan
garages,1.00,1.00,2.00,4.00
furnishing,unfurnished,unfurnished,semi furnished,unfurnished

After inspecting each of the records, it is safe to say that:

1. For `year_built > 2022`, let's just keep the value as it is, since it is better be explained as `building age = 0`.
2. For `year_built in [20010, 20012]`, based on `property_condition`, let's assume best case scenario to be `2010 and 2012`.

In [46]:
def building_age(year_built):
    if year_built <= 2022:
        return (2022 - year_built)
    elif year_built > 2022:
        return 0
    return year_built

building_age_vectd = vectorize(building_age)
df.loc[df.year_built == 20010, 'year_built'] = 2010
df.loc[df.year_built == 20012, 'year_built'] = 2012
df.insert(21, 'building_age', building_age_vectd(df.year_built))

df.building_age.unique()

d:\anaconda3\envs\general_ds\lib\site-packages\numpy\lib\function_base.py:2192: RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)

array([  5.,  nan,   6.,   9.,   8.,   7.,   0.,   2.,  12.,   4.,  11.,
         1.,  16.,  22.,   3.,  15.,  13.,  10.,  18.,  37.,  14.,  21.,
        17.,  28.,  19.,  20.,  27., 152.,  52.,  36.,  42.,  26.,  29.,
        32.,  23.,  34.,  40.,  24.,  46.,  45.,  49., 121.,  30.])

## 5. Considering the Missing Value

Missing values for column fields explained below can naturally be considired as `not provided` so can be replaced by `0` (`lainnya mah` for missing electricity type):

1. Maid Bedrooms
2. Maid Bathrooms
3. Carports
4. Garages
5. Electricity

In [47]:
fill_columns = ['maid_bedrooms', 'maid_bathrooms', 'carports', 'garages']

for column in fill_columns:
    df[column].fillna(0, inplace=True)

df['electricity'].fillna('lainnya mah', inplace=True)
df[
    df.maid_bedrooms.isna() | df.maid_bathrooms.isna() | df.carports.isna() | df.garages.isna() | df.electricity.isna()
    ]

Empty DataFrame
Columns: [url, price_in_rp, title, address, district, city, lat, long, facilities, property_type, ads_id, bedrooms, bathrooms, land_size_m2, building_size_m2, carports, certificate, electricity, maid_bedrooms, maid_bathrooms, floors, building_age, year_built, property_condition, building_orientation, garages, furnishing]
Index: []

[0 rows x 27 columns]

Other than aboves column fields, missing value is considered missing information (since it explains the essential characteristic of the house) and will be evaluated in later analysis.

## 6. Pre-Processed Data

Our preprocessed data looks like below sample:

In [48]:
df[~df.isna()].sample(2).T

,2971,1311
url,https://www.rumah123.com/properti/tangerang/ho...,https://www.rumah123.com/properti/bogor/hos111...
price_in_rp,"1,900,000,000.00","390,000,000.00"
title,Dijual Rumah Neo Catalonia bsd tangerang. Baru,Murah Di Pesona Cilebut Dekat Stasiun Rumah Ca...
address,"BSD City, Tangerang","Cilebut, Bogor"
district,BSD City,Cilebut
city,Tangerang,Bogor
lat,-6.30,-6.53
long,106.59,106.79
facilities,"Keamanan, Kitchen Set, Taman","Taman, Jalur Telepon, Track Lari, Jalur Tel..."
property_type,rumah,rumah
ads_id,hos11365136,hos11159745
bedrooms,3.00,2.00
bathrooms,2.00,1.00
land_size_m2,98.00,72.00
building_size_m2,100.00,45.00
carports,1.00,0.00
certificate,shm - sertifikat hak milik,shm - sertifikat hak milik
electricity,2200 mah,1300 mah
maid_bedrooms,1.00,0.00
maid_bathrooms,1.00,0.00
floors,2.00,1.00
building_age,0.00,4.00
year_built,"2,022.00","2,018.00"
property_condition,baru,bagus
building_orientation,NaN,selatan
garages,0.00,1.00
furnishing,semi furnished,unfurnished

In [49]:
df.to_csv('Scraped_Data/jabodetabek_house_price.csv', index=False)